# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\chats.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChatsWindow(object):
    def setupUi(self, ChatsWindow):
        ChatsWindow.setObjectName("ChatsWindow")
        ChatsWindow.resize(636, 761)
        self.centralwidget = QtWidgets.QWidget(ChatsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 170, 581, 481))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.input_search_username = QtWidgets.QLineEdit(self.centralwidget)
        self.input_search_username.setGeometry(QtCore.QRect(20, 40, 511, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.input_search_username.setFont(font)
        self.input_search_username.setObjectName("input_search_username")
        self.button_search_user = QtWidgets.QPushButton(self.centralwidget)
        self.button_search_user.setGeometry(QtCore.QRect(540, 40, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_search_user.setFont(font)
        self.button_search_user.setObjectName("button_search_user")
        self.label_wrong_username = QtWidgets.QLabel(self.centralwidget)
        self.label_wrong_username.setGeometry(QtCore.QRect(20, 100, 271, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(172, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_wrong_username.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_wrong_username.setFont(font)
        self.label_wrong_username.setAutoFillBackground(False)
        self.label_wrong_username.setObjectName("label_wrong_username")
        self.button_search_back = QtWidgets.QPushButton(self.centralwidget)
        self.button_search_back.setGeometry(QtCore.QRect(540, 90, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_search_back.setFont(font)
        self.button_search_back.setObjectName("button_search_back")
        self.button_exit = QtWidgets.QPushButton(self.centralwidget)
        self.button_exit.setGeometry(QtCore.QRect(20, 677, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_exit.setFont(font)
        self.button_exit.setObjectName("button_exit")
        ChatsWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ChatsWindow)
        self.statusbar.setObjectName("statusbar")
        ChatsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ChatsWindow)
        QtCore.QMetaObject.connectSlotsByName(ChatsWindow)

    def retranslateUi(self, ChatsWindow):
        _translate = QtCore.QCoreApplication.translate
        ChatsWindow.setWindowTitle(_translate("ChatsWindow", "Chats"))
        self.input_search_username.setPlaceholderText(_translate("ChatsWindow", "Введите имя пользователя..."))
        self.button_search_user.setText(_translate("ChatsWindow", "Поиск"))
        self.label_wrong_username.setText(_translate("ChatsWindow", "Пользователя с таким именем не существует"))
        self.button_search_back.setText(_translate("ChatsWindow", "Назад"))
        self.button_exit.setText(_translate("ChatsWindow", "Выйти"))
