# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\single_chat.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SingleChatWindow(object):
    def setupUi(self, SingleChatWindow):
        SingleChatWindow.setObjectName("SingleChatWindow")
        SingleChatWindow.resize(636, 761)
        self.centralwidget = QtWidgets.QWidget(SingleChatWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.messages_browser = QtWidgets.QTextBrowser(self.centralwidget)
        self.messages_browser.setGeometry(QtCore.QRect(20, 80, 591, 551))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.messages_browser.setFont(font)
        self.messages_browser.setObjectName("messages_browser")
        self.input_message = QtWidgets.QTextEdit(self.centralwidget)
        self.input_message.setGeometry(QtCore.QRect(20, 640, 451, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_message.setFont(font)
        self.input_message.setObjectName("input_message")
        self.button_send = QtWidgets.QPushButton(self.centralwidget)
        self.button_send.setGeometry(QtCore.QRect(490, 640, 121, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_send.setFont(font)
        self.button_send.setObjectName("button_send")
        self.label_dialog_with = QtWidgets.QLabel(self.centralwidget)
        self.label_dialog_with.setGeometry(QtCore.QRect(20, 25, 441, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_dialog_with.setFont(font)
        self.label_dialog_with.setObjectName("label_dialog_with")
        self.button_back = QtWidgets.QPushButton(self.centralwidget)
        self.button_back.setGeometry(QtCore.QRect(520, 30, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_back.setFont(font)
        self.button_back.setObjectName("button_back")
        SingleChatWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SingleChatWindow)
        self.statusbar.setObjectName("statusbar")
        SingleChatWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SingleChatWindow)
        QtCore.QMetaObject.connectSlotsByName(SingleChatWindow)

    def retranslateUi(self, SingleChatWindow):
        _translate = QtCore.QCoreApplication.translate
        SingleChatWindow.setWindowTitle(_translate("SingleChatWindow", "SingleChat"))
        self.input_message.setPlaceholderText(_translate("SingleChatWindow", "Введите сообщение..."))
        self.button_send.setText(_translate("SingleChatWindow", "Отправить"))
        self.label_dialog_with.setText(_translate("SingleChatWindow", "text"))
        self.button_back.setText(_translate("SingleChatWindow", "Назад"))
